[package]
name = "two_states"
version = "0.1.0"
edition = "2021"

[dependencies]
ticket_fields = { path = "../../../helpers/ticket_fields" }
[dependencies.uuid]
version = "1.18.1"
# Lets you generate random UUIDs
features = ["v4"]
